### ISSUE TITLE
Browserify support

### ISSUE THREAD

**Issue by kvnneff** [stevenmiller888/matter#1]
Any plans for supporting Browserify?  I know that I could download `dist/` and not run it through Browserify but that's pretty far from ideal.

If not I can work on making the changes to support both Duo and Browserify but I wanted to get your thoughts first.  I think it'd be as easy as changing the `require` calls and getting `segmentio/highlight` a `package.json`.

**Comment by kvnneff** [comment]
Oops!  After looking again at `lib/code.js` there's quite a few deps that would need a `package.json`.  It seems less feasible to me now.

**Comment by stevenmiller888** [comment]
Just published all those modules and pushed up a branch here called [switch_to_browserify](https://github.com/stevenmiller888/matter/tree/switch_to_browserify). Let me know how that branch looks!
